---
version: "3.8"

services:

  dolfinx:
    build:
      context: .
      dockerfile: base.Dockerfile
    container_name: dolfinx
    hostname: dolfinx
    # dns: 8.8.8.8
    command: sshd
    # command: jupyterlab
    ports:
      - target: 22
        published: 22
        mode: host
      - target: 8892
        published: 8892
        mode: host
    volumes:
      - type: bind
        source: ./data
        target: /workspace
    # network_mode: host
    environment:
      # Port to start Jupyter Lab (default: 8888)
      JUPYTERLAB_PORT: 8892
    networks:
      main-network:
        ipv4_address: 172.25.0.7
    restart: always


networks:
  main-network:
    name: main-network
    driver: bridge
    # external: false
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
    attachable: true
